/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Message-Contact/Contact.vue')['default']
    Container: (typeof import('./src/components/Layout/Container.vue'))['default']
    Content: (typeof import('./src/components/Layout/Content.vue'))['default']
    Footer: typeof import('./src/components/Layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/Layout/header/Header.vue')['default']
    Index: typeof import('./src/components/Model/Index.tsx')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    ListContact: typeof import('./src/components/Message-Contact/List-Contact.vue')['default']
    MenuItem: (typeof import('./src/components/Layout/footer/MenuItem.vue'))['default']
    Message: typeof import('./src/components/Message-Contact/Message.vue')['default']
    MessageContact: typeof import('./src/components/Message-Contact/index.vue')['default']
    Model: typeof import('./src/components/Model/Model.vue')['default']
    Operation: typeof import('./src/components/Operation/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingHeader: (typeof import('./src/components/Layout/setting/Settings-Header.vue'))['default']
    SettingItem: (typeof import('./src/components/Layout/setting/Setting-Menu.vue'))['default']
    SettingMenu: typeof import('./src/components/Layout/setting/Setting-Menu.vue')['default']
    Settings: typeof import('./src/components/Layout/setting/Settings.vue')['default']
    SettingsHeader: typeof import('./src/components/Layout/setting/Settings-Header.vue')['default']
    SettingsNav: typeof import('./src/components/Layout/setting/Settings-Nav.vue')['default']
    Toast: typeof import('./src/components/Toast/Toast.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: (typeof import('vant/es'))['Button']
    VanCell: (typeof import('vant/es'))['Cell']
    VanCellGroup: (typeof import('vant/es'))['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCol: (typeof import('vant/es'))['Col']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanIndexAnchor: (typeof import('vant/es'))['IndexAnchor']
    VanIndexBar: (typeof import('vant/es'))['IndexBar']
    VanNavBar: (typeof import('vant/es'))['NavBar']
    VanOverlay: (typeof import('vant/es'))['Overlay']
    VanPicker: (typeof import('vant/es'))['Picker']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: (typeof import('vant/es'))['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanRow: (typeof import('vant/es'))['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
